import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'es' | 'fr' | 'de' | 'zh' | 'ja' | 'ar';

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  en: {
    welcome: 'Welcome back',
    selectMedia: 'Select a media type to begin your content analysis',
    text: 'Text',
    image: 'Image',
    video: 'Video',
    audio: 'Audio',
    history: 'History',
    settings: 'Settings',
    language: 'Language',
    logout: 'Logout',
    login: 'Log In',
    home: 'Home',
    analyzeText: 'Analyze Text',
    analyzeImage: 'Analyze Image',
    analyzeVideo: 'Analyze Video',
    analyzeAudio: 'Analyze Audio',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    profile: 'Profile',
    subscription: 'Subscription',
    signUp: 'Sign Up',
    emailAddress: 'Email Address',
    password: 'Password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot Password?',
    loginPrompt: 'Log in to continue detecting AI content',
    createYourAccount: 'Create Your Account',
    joinToStart: 'Join Unveil to start detecting AI-generated content',
    createAccount: 'Create Account',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    fullName: 'Full Name',
    gender: 'Gender',
    age: 'Age',
    termsOfService: 'Terms of Service',
    privacyPolicy: 'Privacy Policy',
    agreeTerms: 'I agree to the Terms of Service',
    agreePrivacy: 'I agree to the Privacy Policy',
    unveilPlus: 'Unveil Plus',
  },
  es: {
    welcome: 'Bienvenido de nuevo',
    selectMedia: 'Selecciona un tipo de medio para comenzar tu análisis de contenido',
    text: 'Texto',
    image: 'Imagen',
    video: 'Video',
    audio: 'Audio',
    history: 'Historial',
    settings: 'Configuración',
    language: 'Idioma',
    logout: 'Cerrar sesión',
    login: 'Iniciar sesión',
    home: 'Inicio',
    analyzeText: 'Analizar Texto',
    analyzeImage: 'Analizar Imagen',
    analyzeVideo: 'Analizar Video',
    analyzeAudio: 'Analizar Audio',
    darkMode: 'Modo Oscuro',
    lightMode: 'Modo Claro',
    profile: 'Perfil',
    subscription: 'Suscripción',
    signUp: 'Registrarse',
    emailAddress: 'Dirección de correo electrónico',
    password: 'Contraseña',
    rememberMe: 'Recuérdame',
    forgotPassword: '¿Olvidaste tu contraseña?',
    loginPrompt: 'Inicia sesión para seguir detectando contenido de IA',
    createYourAccount: 'Crea tu cuenta',
    joinToStart: 'Únete a Unveil para empezar a detectar contenido generado por IA',
    createAccount: 'Crear cuenta',
    alreadyHaveAccount: '¿Ya tienes una cuenta?',
    dontHaveAccount: '¿No tienes una cuenta?',
    fullName: 'Nombre completo',
    gender: 'Género',
    age: 'Edad',
    termsOfService: 'Términos de servicio',
    privacyPolicy: 'Política de privacidad',
    agreeTerms: 'Acepto los Términos de Servicio',
    agreePrivacy: 'Acepto la Política de Privacidad',
    unveilPlus: 'Unveil Plus',
  },
  fr: {
    welcome: 'Bon retour',
    selectMedia: 'Sélectionnez un type de média pour commencer votre analyse de contenu',
    text: 'Texte',
    image: 'Image',
    video: 'Vidéo',
    audio: 'Audio',
    history: 'Historique',
    settings: 'Paramètres',
    language: 'Langue',
    logout: 'Se déconnecter',
    login: 'Se connecter',
    home: 'Accueil',
    analyzeText: 'Analyser le texte',
    analyzeImage: 'Analyser l\'image',
    analyzeVideo: 'Analyser la vidéo',
    analyzeAudio: 'Analyser l\'audio',
    darkMode: 'Mode Sombre',
    lightMode: 'Mode Clair',
    profile: 'Profil',
    subscription: 'Abonnement',
    signUp: 'S\'inscrire',
    emailAddress: 'Adresse e-mail',
    password: 'Mot de passe',
    rememberMe: 'Se souvenir de moi',
    forgotPassword: 'Mot de passe oublié ?',
    loginPrompt: 'Connectez-vous pour continuer à détecter le contenu IA',
    loggingIn: 'Connexion en cours...',
    createYourAccount: 'Créez votre compte',
    joinToStart: 'Rejoignez Unveil pour commencer à détecter le contenu généré par IA',
    createAccount: 'Créer un compte',
    alreadyHaveAccount: 'Vous avez déjà un compte ?',
    dontHaveAccount: 'Vous n\'avez pas de compte ?',
    fullName: 'Nom complet',
    gender: 'Genre',
    age: 'Âge',
    termsOfService: 'Conditions d\'utilisation',
    privacyPolicy: 'Politique de confidentialité',
    agreeTerms: 'J\'accepte les conditions d\'utilisation',
    agreePrivacy: 'J\'accepte la politique de confidentialité',
    unveilPlus: 'Unveil Plus',
  },
  de: {
    welcome: 'Willkommen zurück',
    selectMedia: 'Wählen Sie einen Medientyp aus, um Ihre Inhaltsanalyse zu beginnen',
    text: 'Text',
    image: 'Bild',
    video: 'Video',
    audio: 'Audio',
    history: 'Verlauf',
    settings: 'Einstellungen',
    language: 'Sprache',
    logout: 'Abmelden',
    login: 'Anmelden',
    home: 'Startseite',
    analyzeText: 'Text analysieren',
    analyzeImage: 'Bild analysieren',
    analyzeVideo: 'Video analysieren',
    analyzeAudio: 'Audio analysieren',
    darkMode: 'Dunkler Modus',
    lightMode: 'Heller Modus',
    profile: 'Profil',
    subscription: 'Abonnement',
    signUp: 'Registrieren',
    emailAddress: 'E-Mail-Adresse',
    password: 'Passwort',
    rememberMe: 'Angemeldet bleiben',
    forgotPassword: 'Passwort vergessen?',
    loginPrompt: 'Melden Sie sich an, um weiterhin KI-Inhalte zu erkennen',
    loggingIn: 'Anmeldung...',
    createYourAccount: 'Erstellen Sie Ihr Konto',
    joinToStart: 'Treten Sie Unveil bei, um mit der Erkennung von KI-generierten Inhalten zu beginnen',
    createAccount: 'Konto erstellen',
    alreadyHaveAccount: 'Haben Sie bereits ein Konto?',
    dontHaveAccount: 'Hast du kein Konto?',
    fullName: 'Vollständiger Name',
    gender: 'Geschlecht',
    age: 'Alter',
    termsOfService: 'Nutzungsbedingungen',
    privacyPolicy: 'Datenschutz-Bestimmungen',
    agreeTerms: 'Ich stimme den Nutzungsbedingungen zu',
    agreePrivacy: 'Ich stimme der Datenschutz-Bestimmung zu',
    unveilPlus: 'Unveil Plus',
  },
  zh: {
    welcome: '欢迎回来',
    selectMedia: '选择媒体类型开始内容分析',
    text: '文本',
    image: '图像',
    video: '视频',
    audio: '音频',
    history: '历史',
    settings: '设置',
    language: '语言',
    logout: '登出',
    login: '登录',
    home: '主页',
    analyzeText: '分析文本',
    analyzeImage: '分析图像',
    analyzeVideo: '分析视频',
    analyzeAudio: '分析音频',
    darkMode: '深色模式',
    lightMode: '浅色模式',
    profile: '个人资料',
    subscription: '订阅',
    signUp: '注册',
    emailAddress: '电子邮件地址',
    password: '密码',
    rememberMe: '记住我',
    forgotPassword: '忘记密码？',
    loginPrompt: '登录以继续检测 AI 内容',
    loggingIn: '登录中...',
    createYourAccount: '创建您的帐户',
    joinToStart: '加入 Unveil 开始检测 AI 生成的内容',
    createAccount: '创建帐户',
    alreadyHaveAccount: '已经有帐户？',
    dontHaveAccount: '还没有帐户？',
    fullName: '全名',
    gender: '性别',
    age: '年龄',
    termsOfService: '服务条款',
    privacyPolicy: '隐私政策',
    agreeTerms: '我同意服务条款',
    agreePrivacy: '我同意隐私政策',
    unveilPlus: 'Unveil Plus',
  },
  ja: {
    welcome: 'おかえりなさい',
    selectMedia: 'コンテンツ分析を開始するメディアタイプを選択してください',
    text: 'テキスト',
    image: '画像',
    video: 'ビデオ',
    audio: 'オーディオ',
    history: '履歴',
    settings: '設定',
    language: '言語',
    logout: 'ログアウト',
    login: 'ログイン',
    home: 'ホーム',
    analyzeText: 'テキストを分析',
    analyzeImage: '画像を分析',
    analyzeVideo: 'ビデオを分析',
    analyzeAudio: 'オーディオを分析',
    darkMode: 'ダークモード',
    lightMode: 'ライトモード',
    profile: 'プロフィール',
    subscription: 'サブスクリプション',
    signUp: 'サインアップ',
    emailAddress: 'メールアドレス',
    password: 'パスワード',
    rememberMe: 'ログイン状態を保持する',
    forgotPassword: 'パスワードをお忘れですか？',
    loginPrompt: 'AI コンテンツの検出を続行するにはログインしてください',
    loggingIn: 'ログイン中...',
    createYourAccount: 'アカウントを作成',
    joinToStart: 'Unveil に参加して AI 生成コンテンツの検出を開始しましょう',
    createAccount: 'アカウントを作成',
    alreadyHaveAccount: 'すでにアカウントをお持ちですか？',
    dontHaveAccount: 'アカウントをお持ちでないですか？',
    fullName: '氏名',
    gender: '性別',
    age: '年齢',
    termsOfService: '利用規約',
    privacyPolicy: 'プライバシーポリシー',
    agreeTerms: '利用規約に同意します',
    agreePrivacy: 'プライバシーポリシーに同意します',
    unveilPlus: 'Unveil Plus',
  },
  ar: {
    welcome: 'مرحبا بعودتك',
    selectMedia: 'حدد نوع الوسائط لبدء تحليل المحتوى',
    text: 'نص',
    image: 'صورة',
    video: 'فيديو',
    audio: 'صوت',
    history: 'التاريخ',
    settings: 'الإعدادات',
    language: 'اللغة',
    logout: 'تسجيل الخروج',
    login: 'تسجيل الدخول',
    home: 'الرئيسية',
    analyzeText: 'تحليل النص',
    analyzeImage: 'تحليل الصورة',
    analyzeVideo: 'تحليل الفيديو',
    analyzeAudio: 'تحليل الصوت',
    darkMode: 'الوضع الداكن',
    lightMode: 'الوضع الفاتح',
    profile: 'الملف الشخصي',
    subscription: 'الاشتراك',
    signUp: 'اشتراك',
    emailAddress: 'عنوان البريد الإلكتروني',
    password: 'كلمة المرور',
    rememberMe: 'تذكرني',
    forgotPassword: 'هل نسيت كلمة السر؟',
    loginPrompt: 'سجّل الدخول لمواصلة اكتشاف محتوى الذكاء الاصطناعي',
    loggingIn: 'جارٍ تسجيل الدخول...',
    createYourAccount: 'أنشئ حسابك',
    joinToStart: 'انضم إلى Unveil لبدء اكتشاف المحتوى الذي أنشأه الذكاء الاصطناعي',
    createAccount: 'إنشاء حساب',
    alreadyHaveAccount: 'هل لديك حساب بالفعل؟',
    dontHaveAccount: 'ليس لديك حساب؟',
    fullName: 'الاسم الكامل',
    gender: 'الجنس',
    age: 'العمر',
    termsOfService: 'شروط الخدمة',
    privacyPolicy: 'سياسة الخصوصية',
    agreeTerms: 'أوافق على شروط الخدمة',
    agreePrivacy: 'أوافق على سياسة الخصوصية',
    unveilPlus: 'Unveil Plus',
  },
};

const languageNames: Record<Language, string> = {
  en: 'English',
  es: 'Español',
  fr: 'Français',
  de: 'Deutsch',
  zh: '中文',
  ja: '日本語',
  ar: 'العربية',
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  availableLanguages: typeof languageNames;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = async (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, availableLanguages: languageNames }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
